export const env = {
  OLD_DATABASE_URL: Deno.env.get("OLD_DATABASE_URL")!,
  NEW_DATABASE_URL: Deno.env.get("NEW_DATABASE_URL")!,
  BETTER_AUTH_SECRET: Deno.env.get("BETTER_AUTH_SECRET")!,
  ALLOWED_ORIGINS: Deno.env.get("ALLOWED_ORIGINS")!,
  DEV_CYCLE_SDK_KEY: Deno.env.get("DEVCYCLE_SERVER_SDK_KEY")!,
};